"""minethon domain models."""

from minethon.models.block import Block
from minethon.models.entity import Entity, EntityKind
from minethon.models.errors import (
    BridgeError,
    MinethonConnectionError,
    InventoryError,
    NavigationError,
    NotSpawnedError,
    PluginError,
    MinethonError,
)
from minethon.models.events import (
    ActionBarEvent,
    BlockBreakProgressEndEvent,
    BlockBreakProgressObservedEvent,
    BlockBrokenEvent,
    BlockPlacedEvent,
    BlockUpdateEvent,
    BossBarCreatedEvent,
    BossBarDeletedEvent,
    BossBarUpdatedEvent,
    BreathEvent,
    ChatEvent,
    ChestLidMoveEvent,
    ChunkColumnLoadEvent,
    ChunkColumnUnloadEvent,
    CollectCompletedEvent,
    DeathEvent,
    DiggingAbortedEvent,
    DiggingCompletedEvent,
    DismountEvent,
    EndEvent,
    EntityAttachEvent,
    EntityAttributesEvent,
    EntityCriticalEffectEvent,
    EntityCrouchEvent,
    EntityDeadEvent,
    EntityDetachEvent,
    EntityEatEvent,
    EntityEatingGrassEvent,
    EntityEffectEndEvent,
    EntityEffectEvent,
    EntityElytraFlewEvent,
    EntityEquipEvent,
    EntityGoneEvent,
    EntityHandSwapEvent,
    EntityHurtEvent,
    EntityMagicCriticalEffectEvent,
    EntityShakingOffWaterEvent,
    EntitySleepEvent,
    EntitySpawnEvent,
    EntitySwingArmEvent,
    EntityTamedEvent,
    EntityTamingEvent,
    EntityUncrouchEvent,
    EntityUpdateEvent,
    EntityWakeEvent,
    ErrorEvent,
    ExperienceEvent,
    ForcedMoveEvent,
    GameEvent,
    GoalFailedEvent,
    GoalReachedEvent,
    HardcodedSoundEffectHeardEvent,
    HealthChangedEvent,
    HeldItemChangedEvent,
    ItemDropEvent,
    KickedEvent,
    LoginEvent,
    MessageEvent,
    MessageStrEvent,
    MountEvent,
    MoveEvent,
    NoteHeardEvent,
    ParticleEvent,
    PhysicsTickEvent,
    PistonMoveEvent,
    PlayerCollectEvent,
    PlayerJoinedEvent,
    PlayerLeftEvent,
    PlayerUpdatedEvent,
    RainEvent,
    ResourcePackEvent,
    RespawnEvent,
    ScoreRemovedEvent,
    ScoreUpdatedEvent,
    ScoreboardCreatedEvent,
    ScoreboardDeletedEvent,
    ScoreboardPositionEvent,
    ScoreboardTitleChangedEvent,
    SleepEvent,
    SoundEffectHeardEvent,
    SpawnEvent,
    SpawnResetEvent,
    TeamCreatedEvent,
    TeamMemberAddedEvent,
    TeamMemberRemovedEvent,
    TeamRemovedEvent,
    TeamUpdatedEvent,
    TimeEvent,
    TitleClearEvent,
    TitleEvent,
    TitleTimesEvent,
    UsedFireworkEvent,
    WakeEvent,
    WeatherUpdateEvent,
    WhisperEvent,
    WindowCloseEvent,
    WindowOpenEvent,
)
from minethon.models.experience import Experience
from minethon.models.game_state import GameState
from minethon.models.item import ItemStack
from minethon.models.player_info import PlayerInfo
from minethon.models.recipe import Recipe
from minethon.models.time_state import TimeState
from minethon.models.vec3 import Vec3
from minethon.models.window import TradeOffer, VillagerSession, WindowHandle

__all__ = [
    # Core types
    "Block",
    "Entity",
    "EntityKind",
    "Experience",
    "GameState",
    "ItemStack",
    "PlayerInfo",
    "Recipe",
    "TimeState",
    "TradeOffer",
    "Vec3",
    "VillagerSession",
    "WindowHandle",
    # Errors
    "BridgeError",
    "InventoryError",
    "MinethonConnectionError",
    "MinethonError",
    "NavigationError",
    "NotSpawnedError",
    "PlayerInfo",
    "PluginError",
    # Lifecycle events
    "DeathEvent",
    "EndEvent",
    "ErrorEvent",
    "GameEvent",
    "KickedEvent",
    "LoginEvent",
    "RespawnEvent",
    "SpawnEvent",
    "SpawnResetEvent",
    # Chat events
    "ActionBarEvent",
    "ChatEvent",
    "MessageEvent",
    "MessageStrEvent",
    "WhisperEvent",
    # Health/state events
    "BreathEvent",
    "ExperienceEvent",
    "HealthChangedEvent",
    "HeldItemChangedEvent",
    "SleepEvent",
    "WakeEvent",
    # World events
    "BlockBrokenEvent",
    "BlockPlacedEvent",
    "BlockUpdateEvent",
    "ChunkColumnLoadEvent",
    "ChunkColumnUnloadEvent",
    "RainEvent",
    "TimeEvent",
    "WeatherUpdateEvent",
    "ResourcePackEvent",
    "TitleEvent",
    "TitleTimesEvent",
    "TitleClearEvent",
    # Entity events
    "EntityAttachEvent",
    "EntityAttributesEvent",
    "EntityCriticalEffectEvent",
    "EntityCrouchEvent",
    "EntityDeadEvent",
    "EntityDetachEvent",
    "EntityEatEvent",
    "EntityEatingGrassEvent",
    "EntityEffectEndEvent",
    "EntityEffectEvent",
    "EntityElytraFlewEvent",
    "EntityEquipEvent",
    "EntityGoneEvent",
    "EntityHandSwapEvent",
    "EntityHurtEvent",
    "EntityMagicCriticalEffectEvent",
    "EntityShakingOffWaterEvent",
    "EntitySleepEvent",
    "EntitySpawnEvent",
    "EntitySwingArmEvent",
    "EntityTamedEvent",
    "EntityTamingEvent",
    "EntityUncrouchEvent",
    "EntityUpdateEvent",
    "EntityWakeEvent",
    "ItemDropEvent",
    "PlayerCollectEvent",
    # Player events
    "PlayerJoinedEvent",
    "PlayerLeftEvent",
    "PlayerUpdatedEvent",
    # Navigation events
    "GoalFailedEvent",
    "GoalReachedEvent",
    # Collection events
    "CollectCompletedEvent",
    # Block interaction events
    "BlockBreakProgressEndEvent",
    "BlockBreakProgressObservedEvent",
    "ChestLidMoveEvent",
    "DiggingAbortedEvent",
    "DiggingCompletedEvent",
    "PistonMoveEvent",
    # Sound events
    "HardcodedSoundEffectHeardEvent",
    "NoteHeardEvent",
    "SoundEffectHeardEvent",
    # Movement events
    "DismountEvent",
    "ForcedMoveEvent",
    "MountEvent",
    "MoveEvent",
    "PhysicsTickEvent",
    # Window events
    "WindowCloseEvent",
    "WindowOpenEvent",
    # Scoreboard/team/bossbar events
    "BossBarCreatedEvent",
    "BossBarDeletedEvent",
    "BossBarUpdatedEvent",
    "ScoreRemovedEvent",
    "ScoreUpdatedEvent",
    "ScoreboardCreatedEvent",
    "ScoreboardDeletedEvent",
    "ScoreboardPositionEvent",
    "ScoreboardTitleChangedEvent",
    "TeamCreatedEvent",
    "TeamMemberAddedEvent",
    "TeamMemberRemovedEvent",
    "TeamRemovedEvent",
    "TeamUpdatedEvent",
    # Other events
    "ParticleEvent",
    "UsedFireworkEvent",
]
